import { NextRequest, NextResponse } from "next/server";

// Mock data for now - will be replaced with real Job Nimbus API calls
const workflowData: Record<string, any> = {
  "roof-replacement": {
    overallConversion: 35,
    avgCycleTime: 24,
    activeJobs: 47,
    ytdRevenue: 245000,
    conversions: {
      "Lead": 85,
      "Contacting": 78,
      "Appointment Scheduled": 92,
      "Estimating": 88,
      "Estimate Sent": 45,
      "Signed Contract": 95,
      "Pre-Production": 98,
      "Ready for Install": 100,
      "Job Scheduled": 98,
      "In Progress": 95,
      "Job Completed": 92,
      "Invoiced Customer": 88,
      "Paid & Closed": 100,
    },
    avgDays: {
      "Lead": 2,
      "Contacting": 3,
      "Appointment Scheduled": 5,
      "Estimating": 4,
      "Estimate Sent": 7,
      "Signed Contract": 3,
      "Pre-Production": 5,
      "Ready for Install": 2,
      "Job Scheduled": 3,
      "In Progress": 4,
      "Job Completed": 2,
      "Invoiced Customer": 8,
      "Paid & Closed": 5,
    },
    statusCounts: {
      "Lead": 45,
      "Contacting": 38,
      "Appointment Scheduled": 29,
      "Estimating": 27,
      "Estimate Sent": 23,
      "Signed Contract": 10,
      "Pre-Production": 9,
      "Ready for Install": 9,
      "Job Scheduled": 8,
      "In Progress": 8,
      "Job Completed": 7,
      "Invoiced Customer": 6,
      "Paid & Closed": 5,
      "Request Review": 0,
    },
  },
  insurance: {
    overallConversion: 42,
    avgCycleTime: 35,
    activeJobs: 62,
    ytdRevenue: 387000,
    conversions: {
      "Lead": 82,
      "Contacting": 75,
      "Appointment Scheduled": 90,
      "Waiting on Adjuster": 85,
      "Estimating": 80,
      "Estimate Sent": 55,
      "Signed Contract": 93,
      "Supplementing": 88,
      "Pre-Production": 95,
      "Ready for Install": 98,
      "Job Scheduled": 97,
      "In Progress": 94,
      "Job Completed": 90,
      "Invoiced Insurance": 92,
      "Paid & Closed": 100,
    },
    avgDays: {
      "Lead": 2,
      "Contacting": 3,
      "Appointment Scheduled": 6,
      "Waiting on Adjuster": 12,
      "Estimating": 5,
      "Estimate Sent": 9,
      "Signed Contract": 4,
      "Supplementing": 8,
      "Pre-Production": 6,
      "Ready for Install": 3,
      "Job Scheduled": 4,
      "In Progress": 5,
      "Job Completed": 3,
      "Invoiced Insurance": 14,
      "Paid & Closed": 7,
    },
    statusCounts: {
      "Lead": 52,
      "Contacting": 42,
      "Appointment Scheduled": 38,
      "Waiting on Adjuster": 32,
      "Estimating": 27,
      "Estimate Sent": 21,
      "Signed Contract": 11,
      "Supplementing": 10,
      "Pre-Production": 9,
      "Ready for Install": 8,
      "Job Scheduled": 8,
      "In Progress": 7,
      "Job Completed": 6,
      "Invoiced Insurance": 5,
      "Paid & Closed": 5,
      "Request Review": 0,
    },
  },
  repairs: {
    overallConversion: 58,
    avgCycleTime: 12,
    activeJobs: 28,
    ytdRevenue: 89000,
    conversions: {
      "New Lead": 88,
      "Contacting": 82,
      "Appointment Scheduled": 90,
      "Estimating": 85,
      "Estimate Sent": 65,
      "Signed Contract": 95,
      "Repair Scheduled": 98,
      "Repair in Progress": 96,
      "Job Complete": 94,
      "Invoice Sent": 90,
      "Paid & Closed": 100,
    },
    avgDays: {
      "New Lead": 1,
      "Contacting": 2,
      "Appointment Scheduled": 3,
      "Estimating": 2,
      "Estimate Sent": 4,
      "Signed Contract": 2,
      "Repair Scheduled": 3,
      "Repair in Progress": 1,
      "Job Complete": 1,
      "Invoice Sent": 5,
      "Paid & Closed": 3,
    },
    statusCounts: {
      "New Lead": 32,
      "Contacting": 28,
      "Appointment Scheduled": 23,
      "Estimating": 20,
      "Estimate Sent": 17,
      "Signed Contract": 11,
      "Repair Scheduled": 10,
      "Repair in Progress": 9,
      "Job Complete": 8,
      "Invoice Sent": 7,
      "Paid & Closed": 6,
      "Request Review": 0,
    },
  },
  "real-estate": {
    overallConversion: 68,
    avgCycleTime: 18,
    activeJobs: 19,
    ytdRevenue: 156000,
    conversions: {
      "Lead": 90,
      "Contacting": 85,
      "Appointment Scheduled": 95,
      "Estimating": 92,
      "Estimate Sent": 75,
      "Signed Contract": 98,
      "Pre-Production": 97,
      "Ready for Install": 98,
      "Job Scheduled": 97,
      "In Progress": 95,
      "Job Complete": 93,
      "Invoice Sent": 95,
      "Paid & Closed": 100,
    },
    avgDays: {
      "Lead": 1,
      "Contacting": 2,
      "Appointment Scheduled": 3,
      "Estimating": 3,
      "Estimate Sent": 5,
      "Signed Contract": 2,
      "Pre-Production": 4,
      "Ready for Install": 2,
      "Job Scheduled": 3,
      "In Progress": 4,
      "Job Complete": 2,
      "Invoice Sent": 6,
      "Paid & Closed": 4,
    },
    statusCounts: {
      "Lead": 18,
      "Contacting": 16,
      "Appointment Scheduled": 13,
      "Estimating": 12,
      "Estimate Sent": 11,
      "Signed Contract": 8,
      "Pre-Production": 7,
      "Ready for Install": 7,
      "Job Scheduled": 6,
      "In Progress": 5,
      "Job Complete": 4,
      "Invoice Sent": 3,
      "Paid & Closed": 3,
      "Request Review": 0,
    },
  },
  "maintenance-plan": {
    overallConversion: 72,
    avgCycleTime: 8,
    activeJobs: 15,
    ytdRevenue: 34000,
    conversions: {
      "Lead": 92,
      "Contacting": 88,
      "Appointment Scheduled": 95,
      "Estimating": 90,
      "Estimate Sent": 80,
      "Signed Contract": 98,
      "Plan Active": 100,
      "Invoice Sent": 95,
      "Paid & Closed": 100,
    },
    avgDays: {
      "Lead": 1,
      "Contacting": 2,
      "Appointment Scheduled": 2,
      "Estimating": 1,
      "Estimate Sent": 3,
      "Signed Contract": 1,
      "Plan Active": 365,
      "Invoice Sent": 4,
      "Paid & Closed": 2,
    },
    statusCounts: {
      "Lead": 12,
      "Contacting": 11,
      "Appointment Scheduled": 9,
      "Estimating": 8,
      "Estimate Sent": 7,
      "Signed Contract": 5,
      "Plan Active": 5,
      "Invoice Sent": 5,
      "Paid & Closed": 4,
    },
  },
  legacy: {
    overallConversion: 38,
    avgCycleTime: 28,
    activeJobs: 34,
    ytdRevenue: 178000,
    conversions: {
      "Lead": 80,
      "Contacting": 75,
      "Appointment Scheduled": 88,
      "Estimating": 82,
      "Estimate Sent": 48,
      "Signed Contract": 92,
      "In Production": 95,
      "Job Complete": 90,
      "Invoice Sent": 85,
      "Paid & Closed": 100,
    },
    avgDays: {
      "Lead": 3,
      "Contacting": 4,
      "Appointment Scheduled": 6,
      "Estimating": 5,
      "Estimate Sent": 8,
      "Signed Contract": 4,
      "In Production": 12,
      "Job Complete": 3,
      "Invoice Sent": 9,
      "Paid & Closed": 6,
    },
    statusCounts: {
      "Lead": 28,
      "Contacting": 22,
      "Appointment Scheduled": 19,
      "Estimating": 16,
      "Estimate Sent": 13,
      "Signed Contract": 6,
      "In Production": 5,
      "Job Complete": 4,
      "Invoice Sent": 3,
      "Paid & Closed": 3,
    },
  },
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ workflowType: string }> }
) {
  const { workflowType } = await params;
  const data = workflowData[workflowType];

  if (!data) {
    return NextResponse.json(
      { error: "Workflow not found" },
      { status: 404 }
    );
  }

  return NextResponse.json(data);
}
